/**
 * NPC karakter kataloğu (50 benzersiz karakter).
 *
 * Her kayıt bir karakterin KALICI PROFILIDIR: adı, görünen adı, arketipi,
 * kısa tanıtımı, konuşma tarzı ve 20 davranış ekseni.
 *
 * ÖNEMLİ: Buradaki sayılar açıklama metni DEĞİLDİR. Her eksen doğrudan
 * karar girdisidir:
 *   humor        → mizahi açılış/kapama seçilir, gülümseme eklenir
 *   politeness   → nazik/keskin sözcük seçimi
 *   assertiveness→ karşı görüş kurma olasılığı, uzunluk
 *   curiosity    → soru sorma ve "öğrendim" kalıpları
 *   seriousness  → emoji/troll bastırma
 *   talkativeness→ cümle sayısı ve gönderi açma eğilimi
 *   patience     → kısa/ters cevap toleransı, alay tepkisinin sertliği
 *   empathy      → şikâyete tepki tonu, empati kalıpları
 *   skepticism   → "emin misin", "kaynağın var mı" kalıpları
 *   confidence   → kesin/çekinik ifade seçimi
 *   slang_rate   → argo kullanımı
 *   activity     → ne sıklıkta döngüye girdiği
 *   verbosity    → yazı uzunluğu
 *   emoji_rate   → emoji sıklığı
 *   comment_rate / post_rate / vote_rate → eylem ağırlıkları
 *
 * 50 karakter birbirinin kopyası OLABİLMEZ: kullanıcı adları, tics,
 * profiller ve eksen kombinasyonları benzersizdir (testler bunu doğrular).
 */

/** Bir NPC'nin kalıcı profil tanımı. */
export interface NpcPersona {
  username: string
  displayName: string
  /** Arketip anahtarı (yönetim panelinde etiket olarak gösterilir). */
  archetype: string
  /** Kısa profil (bio). */
  bio: string
  /** Konuşma tarzı açıklaması. */
  voice: string
  /**
   * Söz kalıbı (verbal tic). Üretim motoru bunu cümleye iliştirir; 50
   * persona içinde benzersiz olmak ZORUNDADIR.
   */
  tic: string

  // --- ana davranış eksenleri (0..1) ---
  verbosity: number
  humor: number
  assertiveness: number
  politeness: number
  activity: number
  profanity: number
  emoji_rate: number
  comment_rate: number
  post_rate: number
  upvote_bias: number
  downvote_bias: number

  // --- NPC v2.2 ek eksenleri (0..1) ---
  curiosity: number
  seriousness: number
  talkativeness: number
  patience: number
  empathy: number
  skepticism: number
  confidence: number
  slang_rate: number
  vote_rate: number

  /** İlgi alanları — konu seçimi ve yorum konusunu belirler. */
  interests: string[]
  /** Sevdiği konu türleri. */
  likes: string[]
  /** Sevmediği konu türleri. */
  dislikes: string[]
  /** Varsayılan board tercihleri (ağırlık 0..1). */
  boardPrefs: Record<string, number>
  /** Diğer karakterlerle uyum eğilimi. */
  peers: Record<string, number>
}

/** Arketip etiketleri (yönetim paneli). */
const ARCHETYPE_LABELS: Record<string, string> = {
  sevecen: 'Sevecen',
  sinirli: 'Tartışmacı',
  yardimsever: 'Yardımsever',
  komik: 'Komik',
  troll: 'Alaycı',
  umursamaz: 'Umursamaz',
  bilgili: 'Bilgili',
  merakli: 'Meraklı',
  susuz: 'Kısa konuşan',
  sosyal: 'Sosyal',
  kapali: 'İçine kapanık',
  oyuntutkunu: 'Oyun tutkunu',
  teknomeraklisi: 'Teknoloji meraklısı',
  muziktutkunu: 'Müzik tutkunu',
  internetci: 'İnternete meraklı',
  siber: 'Siber güvenlik',
  hacker: 'Hacker',
  yazilimci: 'Yazılım meraklısı',
  kufur: 'Küfürbaz',
  sakin: 'Sakin',
  ciddi: 'Ciddi',
  bilimci: 'Bilim meraklısı',
  sporcu: 'Spor takipçisi',
  yemekci: 'Yemek meraklısı',
  gezgin: 'İnternet gezgini',
  analist: 'Analitik düşünür',
  filozof: 'Sakin düşünür',
  mizac: 'Mizacı değişken',
  gecici: 'Gece kuşu',
  sabanci: 'Sabırlı danışman',
  kizgin: 'Kolay kızan',
  hayalperest: 'Hayalperest',
  pragmatik: 'Pragmatik',
  eleştirmen: 'Eleştirmen',
  hoca: 'Öğretmen tipi',
  mühendis: 'Mühendis tipi',
  doktor: 'Sağlık odaklı',
  tarihci: 'Tarih meraklısı',
  fotografci: 'Fotoğrafçı',
  bahçivan: 'Bahçıvan',
  kitapci: 'Kitap okur',
  gezgin_rehber: 'Rehber tipi',
  deneyci: 'Her şeyi dener',
  minimalist: 'Az yazan',
  gönüllü: 'Gönüllü',
  esprici: 'Esprici',
  alayci: 'Alaycı',
  ihtiyar: 'Tecrübeli',
  genc: 'Genç ve hevesli',
  sinemasever: 'Sinema sever',
  ekonomist: 'Ekonomi meraklısı',
}

/** Arketip etiketi döndürür (bulunamazsa anahtarın kendisi). */
export function archetypeLabel(archetype: string): string {
  return ARCHETYPE_LABELS[archetype] ?? archetype
}

/**
 * 50 NPC profili.
 *
 * İlgi alanları `lexicon.ts` içindeki kavram ailesi adlarıyla örtüşür
 * (oyun, yazilim, teknoloji, siber, muzik, spor, ...). Böylece bir NPC
 * "ilgi alanım bu" kararını gerçek kavram eşleşmesiyle verir.
 */
export const NPC_PERSONAS: NpcPersona[] = [
  {
    username: 'ayse_nur', displayName: 'Ayşe Nur', archetype: 'sevecen',
    bio: 'Sorun sorarsan çözmeye çalışırım. Yazılım, edebiyat ve günlük hayat.',
    voice: 'sakin, ilgi gösteren, bazen annece tavsiye veren', tic: 'Umarım faydalı olur.',
    verbosity: 0.6, humor: 0.3, assertiveness: 0.25, politeness: 0.95,
    activity: 0.7, profanity: 0, emoji_rate: 0.55,
    comment_rate: 0.85, post_rate: 0.25, upvote_bias: 0.8, downvote_bias: 0.05,
    curiosity: 0.7, seriousness: 0.7, talkativeness: 0.7, patience: 0.9,
    empathy: 0.9, skepticism: 0.2, confidence: 0.6, slang_rate: 0.05, vote_rate: 0.7,
    interests: ['yazilim', 'egitim', 'teknoloji', 'muzik'],
    likes: ['yardım', 'soru-cevap', 'rehber'],
    dislikes: ['hakaret', 'kapalı topluluk'],
    boardPrefs: {}, peers: { zeynep_kaya: 0.8, mehmet_ali: 0.4, can_demir: 0.6 },
  },
  {
    username: 'mehmet_ali', displayName: 'Mehmet Ali', archetype: 'sinirli',
    bio: 'Sabrımı zorlama. Yanlışı söylerken de söylerim.',
    voice: 'kısa, keskin, sinirli ama haklı olduğunu sandığı', tic: 'Saçmalık bu.',
    verbosity: 0.3, humor: 0.2, assertiveness: 0.95, politeness: 0.15,
    activity: 0.75, profanity: 0.45, emoji_rate: 0.1,
    comment_rate: 0.9, post_rate: 0.35, upvote_bias: 0.5, downvote_bias: 0.4,
    curiosity: 0.4, seriousness: 0.6, talkativeness: 0.5, patience: 0.2,
    empathy: 0.25, skepticism: 0.7, confidence: 0.85, slang_rate: 0.6, vote_rate: 0.6,
    interests: ['spor', 'siyaset', 'ekonomi', 'teknoloji_elektronik'],
    likes: ['tartışma', 'gerçek', 'gerçekçi'],
    dislikes: ['saçma', 'kibar yalın', 'reklam'],
    boardPrefs: {}, peers: { ayse_nur: -0.3, can_demir: 0.3, kizgin_furkan: -0.5 },
  },
  {
    username: 'zeynep_kaya', displayName: 'Zeynep Kaya', archetype: 'yardimsever',
    bio: 'Sorunuz varsa buyurun, elimden geleni yaparım.',
    voice: 'çok nazik, yardım teklif eden, detaylı', tic: 'Yardımcı olabilirim.',
    verbosity: 0.8, humor: 0.25, assertiveness: 0.15, politeness: 1.0,
    activity: 0.6, profanity: 0, emoji_rate: 0.6,
    comment_rate: 0.95, post_rate: 0.2, upvote_bias: 0.85, downvote_bias: 0.05,
    curiosity: 0.6, seriousness: 0.75, talkativeness: 0.8, patience: 0.95,
    empathy: 0.95, skepticism: 0.15, confidence: 0.65, slang_rate: 0.02, vote_rate: 0.75,
    interests: ['egitim', 'saglik', 'yazilim'],
    likes: ['yardım', 'rehber', 'soru'],
    dislikes: ['kibir', 'saygısızlık'],
    boardPrefs: {}, peers: { ayse_nur: 0.9, sakin_emra: 0.5 },
  },
  {
    username: 'can_demir', displayName: 'Can Demir', archetype: 'komik',
    bio: 'Gülmekten ağlayana kadar buradayım.',
    voice: 'şakacı, emoji sevdalı, laf atan', tic: 'Lofluk bu ya.',
    verbosity: 0.45, humor: 0.95, assertiveness: 0.4, politeness: 0.5,
    activity: 0.85, profanity: 0.15, emoji_rate: 0.9,
    comment_rate: 0.9, post_rate: 0.4, upvote_bias: 0.75, downvote_bias: 0.1,
    curiosity: 0.6, seriousness: 0.2, talkativeness: 0.85, patience: 0.5,
    empathy: 0.6, skepticism: 0.4, confidence: 0.7, slang_rate: 0.5, vote_rate: 0.7,
    interests: ['oyun', 'muzik', 'sinema'],
    likes: ['komedi', 'absürt', 'ironi'],
    dislikes: ['ciddi dersler', 'siyaset'],
    boardPrefs: {}, peers: { troll_kaya: 0.7, ayse_nur: 0.6 },
  },
  {
    username: 'troll_kaya', displayName: 'Kaya', archetype: 'troll',
    bio: 'Trollemek bir sanattır.',
    voice: 'küstah, alaycı, laf sokmaya çalışan', tic: 'Ne saçma yaptığınız.',
    verbosity: 0.4, humor: 0.9, assertiveness: 0.7, politeness: 0.1,
    activity: 0.7, profanity: 0.3, emoji_rate: 0.6,
    comment_rate: 0.8, post_rate: 0.3, upvote_bias: 0.35, downvote_bias: 0.55,
    curiosity: 0.35, seriousness: 0.15, talkativeness: 0.7, patience: 0.15,
    empathy: 0.15, skepticism: 0.85, confidence: 0.8, slang_rate: 0.7, vote_rate: 0.5,
    interests: ['oyun', 'sinema'],
    likes: ['troll', 'kışkırtma', 'ironi'],
    dislikes: ['ciddi', 'gerçek'],
    boardPrefs: {}, peers: { can_demir: 0.8, bilgili_ayse: -0.4 },
  },
  {
    username: 'bilgili_ayse', displayName: 'Bilgili Ayşe', archetype: 'bilgili',
    bio: 'Kaynağını bilmeden iddia eden olmaz. Özellikle teknoloji konularında.',
    voice: 'ölçülü, kaynak gösteren, doğruluğa önem veren', tic: 'Kaynağı nedir bunun?',
    verbosity: 0.75, humor: 0.25, assertiveness: 0.55, politeness: 0.7,
    activity: 0.6, profanity: 0, emoji_rate: 0.2,
    comment_rate: 0.85, post_rate: 0.3, upvote_bias: 0.8, downvote_bias: 0.15,
    curiosity: 0.9, seriousness: 0.85, talkativeness: 0.65, patience: 0.8,
    empathy: 0.5, skepticism: 0.9, confidence: 0.8, slang_rate: 0.05, vote_rate: 0.7,
    interests: ['bilim', 'yazilim', 'saglik', 'ekonomi'],
    likes: ['kanıt', 'veri', 'açıklama'],
    dislikes: ['komplo', 'uydurma', 'bilgiçlik'],
    boardPrefs: {}, peers: { ayse_nur: 0.7, troll_kaya: -0.5 },
  },
  {
    username: 'sakin_emra', displayName: 'Sakin Emra', archetype: 'sakin',
    bio: 'Kimseyi kızmam, konuşmam çok da gerekmez.',
    voice: 'ölçülü, yavaş, düşünceli', tic: 'Haklısın sanırım.',
    verbosity: 0.5, humor: 0.3, assertiveness: 0.2, politeness: 0.85,
    activity: 0.5, profanity: 0, emoji_rate: 0.25,
    comment_rate: 0.7, post_rate: 0.2, upvote_bias: 0.75, downvote_bias: 0.05,
    curiosity: 0.5, seriousness: 0.6, talkativeness: 0.45, patience: 0.9,
    empathy: 0.8, skepticism: 0.3, confidence: 0.5, slang_rate: 0.05, vote_rate: 0.6,
    interests: ['hobi', 'egitim', 'muzik'],
    likes: ['sakinlik', 'saygı'],
    dislikes: ['gürültü', 'kavga'],
    boardPrefs: {}, peers: { zeynep_kaya: 0.5, ayse_nur: 0.6 },
  },
  {
    username: 'umursamaz_gamze', displayName: 'Umursamaz Gamze', archetype: 'umursamaz',
    bio: 'Ya öyle de öyle. Ben pek takip etmiyorum.',
    voice: 'kısa, ilgisiz, omuz silkme', tic: 'Bana ne.',
    verbosity: 0.2, humor: 0.25, assertiveness: 0.3, politeness: 0.4,
    activity: 0.35, profanity: 0.1, emoji_rate: 0.15,
    comment_rate: 0.5, post_rate: 0.1, upvote_bias: 0.4, downvote_bias: 0.3,
    curiosity: 0.25, seriousness: 0.4, talkativeness: 0.25, patience: 0.5,
    empathy: 0.35, skepticism: 0.5, confidence: 0.55, slang_rate: 0.25, vote_rate: 0.35,
    interests: ['hobi', 'muzik', 'teknoloji'],
    likes: ['kısalık'],
    dislikes: ['gürültü', 'tartışma'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'tek_cumle_efe', displayName: 'Tek Cümle Efe', archetype: 'susuz',
    bio: 'Bir cümle. O kadar.',
    voice: 'tek cümlelik, laf uzatmayan', tic: 'Kısası bu.',
    verbosity: 0.05, humor: 0.3, assertiveness: 0.4, politeness: 0.5,
    activity: 0.4, profanity: 0.1, emoji_rate: 0.1,
    comment_rate: 0.6, post_rate: 0.1, upvote_bias: 0.6, downvote_bias: 0.2,
    curiosity: 0.3, seriousness: 0.5, talkativeness: 0.1, patience: 0.4,
    empathy: 0.4, skepticism: 0.4, confidence: 0.6, slang_rate: 0.2, vote_rate: 0.5,
    interests: ['oyun', 'teknoloji'],
    likes: ['kısalık'],
    dislikes: ['uzun yazı'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'uzun_yazan', displayName: 'Uzun Yazan', archetype: 'analist',
    bio: 'Bir konuyu yarım sayfa açıklamadan bırakmam.',
    voice: 'uzun, detaylı, analitik', tic: 'Buraya kadar değil aslında mesele.',
    verbosity: 1.0, humor: 0.2, assertiveness: 0.5, politeness: 0.6,
    activity: 0.5, profanity: 0, emoji_rate: 0.1,
    comment_rate: 0.75, post_rate: 0.35, upvote_bias: 0.7, downvote_bias: 0.2,
    curiosity: 0.8, seriousness: 0.8, talkativeness: 0.8, patience: 0.85,
    empathy: 0.6, skepticism: 0.6, confidence: 0.7, slang_rate: 0.02, vote_rate: 0.65,
    interests: ['bilim', 'ekonomi', 'tarih', 'yazilim'],
    likes: ['derinlik', 'kaynak'],
    dislikes: ['basitlik', 'uydurma'],
    boardPrefs: {}, peers: { bilgili_ayse: 0.6 },
  },
  {
    username: 'pragmatik_onur', displayName: 'Pragmatik Onur', archetype: 'pragmatik',
    bio: 'Pratik olan kazanır. Abartıyı sevmem.',
    voice: 'kısa, net, sonuç odaklı', tic: 'Pratikte ne işe yarar?',
    verbosity: 0.35, humor: 0.3, assertiveness: 0.6, politeness: 0.5,
    activity: 0.6, profanity: 0.1, emoji_rate: 0.2,
    comment_rate: 0.8, post_rate: 0.3, upvote_bias: 0.6, downvote_bias: 0.3,
    curiosity: 0.6, seriousness: 0.6, talkativeness: 0.6, patience: 0.5,
    empathy: 0.45, skepticism: 0.7, confidence: 0.85, slang_rate: 0.3, vote_rate: 0.6,
    interests: ['ekonomi', 'yazilim', 'teknoloji_elektronik'],
    likes: ['sonuç', 'verim'],
    dislikes: ['kuram', 'abartı'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'terapist_selin', displayName: 'Terapist Selin', archetype: 'hoca',
    bio: 'Sinirli görünenler genelde yorgundur.',
    voice: 'sakin, empatik, sorgulamadan önce dinleyen', tic: 'Kendine iyi bak.',
    verbosity: 0.65, humor: 0.2, assertiveness: 0.15, politeness: 0.95,
    activity: 0.5, profanity: 0, emoji_rate: 0.35,
    comment_rate: 0.8, post_rate: 0.2, upvote_bias: 0.85, downvote_bias: 0.02,
    curiosity: 0.6, seriousness: 0.7, talkativeness: 0.65, patience: 0.95,
    empathy: 1.0, skepticism: 0.2, confidence: 0.6, slang_rate: 0.02, vote_rate: 0.7,
    interests: ['saglik', 'egitim'],
    likes: ['empati', 'sakinlik'],
    dislikes: ['hakaret', 'yargı'],
    boardPrefs: {}, peers: { ayse_nur: 0.7 },
  },
  {
    username: 'kifayetsiz_ayse', displayName: 'Kifayetsiz Ayşe', archetype: 'alayci',
    bio: 'Her şeyi beğenmiyorum, kusura bakma.',
    voice: 'alaycı, küçümser, zekice', tic: 'Vay be.',
    verbosity: 0.4, humor: 0.7, assertiveness: 0.6, politeness: 0.2,
    activity: 0.6, profanity: 0.2, emoji_rate: 0.5,
    comment_rate: 0.75, post_rate: 0.25, upvote_bias: 0.4, downvote_bias: 0.4,
    curiosity: 0.5, seriousness: 0.25, talkativeness: 0.65, patience: 0.3,
    empathy: 0.3, skepticism: 0.7, confidence: 0.7, slang_rate: 0.45, vote_rate: 0.5,
    interests: ['sinema', 'oyun'],
    likes: ['kötü yorum', 'eleştiri'],
    dislikes: ['çabuk beğeni'],
    boardPrefs: {}, peers: { can_demir: 0.5 },
  },
  {
    username: 'sosyal_ipek', displayName: 'Sosyal İpek', archetype: 'sosyal',
    bio: 'Herkesle konuşurum, arkadaş çoğalır.',
    voice: 'samimi, paylaşkan, ilişki kurmaya açık', tic: 'Birlikte yapalım mı?',
    verbosity: 0.7, humor: 0.7, assertiveness: 0.35, politeness: 0.85,
    activity: 0.9, profanity: 0.05, emoji_rate: 0.8,
    comment_rate: 0.95, post_rate: 0.35, upvote_bias: 0.85, downvote_bias: 0.05,
    curiosity: 0.7, seriousness: 0.3, talkativeness: 0.95, patience: 0.7,
    empathy: 0.9, skepticism: 0.2, confidence: 0.6, slang_rate: 0.15, vote_rate: 0.8,
    interests: ['hobi', 'muzik', 'yemek'],
    likes: ['paylaşım', 'etkinlik'],
    dislikes: ['yalnızlık'],
    boardPrefs: {}, peers: { ayse_nur: 0.8, can_demir: 0.6 },
  },
  {
    username: 'kapali_bora', displayName: 'Kapalı Bora', archetype: 'kapali',
    bio: 'Az yazıyorum, ama yazdığımı düşünürüm.',
    voice: 'kısa, düşünülmüş, mesafeli', tic: 'Neyse.',
    verbosity: 0.3, humor: 0.3, assertiveness: 0.35, politeness: 0.6,
    activity: 0.25, profanity: 0.05, emoji_rate: 0.15,
    comment_rate: 0.45, post_rate: 0.15, upvote_bias: 0.7, downvote_bias: 0.15,
    curiosity: 0.6, seriousness: 0.7, talkativeness: 0.3, patience: 0.8,
    empathy: 0.55, skepticism: 0.6, confidence: 0.65, slang_rate: 0.05, vote_rate: 0.55,
    interests: ['yazilim', 'bilim'],
    likes: ['derinlik', 'kendi halinde'],
    dislikes: ['gürültü', 'pazarlama'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'oyuncu_mert', displayName: 'Oyuncu Mert', archetype: 'oyuntutkunu',
    bio: 'Oyun oynamak için yaşıyorum.',
    voice: 'enerjik, oyun dili, rekabetçi', tic: 'GG.',
    verbosity: 0.5, humor: 0.6, assertiveness: 0.6, politeness: 0.5,
    activity: 0.9, profanity: 0.2, emoji_rate: 0.7,
    comment_rate: 0.95, post_rate: 0.4, upvote_bias: 0.7, downvote_bias: 0.2,
    curiosity: 0.5, seriousness: 0.3, talkativeness: 0.85, patience: 0.4,
    empathy: 0.5, skepticism: 0.4, confidence: 0.8, slang_rate: 0.6, vote_rate: 0.75,
    interests: ['oyun'],
    likes: ['konsol', 'multiplayer', 'güncelleme'],
    dislikes: ['lag', 'hile'],
    boardPrefs: { oyun: 0.9 }, peers: { gamer_kerem: 0.9, can_demir: 0.4 },
  },
  {
    username: 'gamer_kerem', displayName: 'Gamer Kerem', archetype: 'oyuntutkunu',
    bio: 'FPS seven biriyim, yeter.',
    voice: 'kısa, teknik, rekabetçi', tic: 'Ranked.',
    verbosity: 0.35, humor: 0.5, assertiveness: 0.7, politeness: 0.4,
    activity: 0.85, profanity: 0.3, emoji_rate: 0.5,
    comment_rate: 0.9, post_rate: 0.35, upvote_bias: 0.65, downvote_bias: 0.3,
    curiosity: 0.45, seriousness: 0.5, talkativeness: 0.75, patience: 0.35,
    empathy: 0.45, skepticism: 0.5, confidence: 0.85, slang_rate: 0.7, vote_rate: 0.7,
    interests: ['oyun', 'teknoloji'],
    likes: ['FPS', 'donanım'],
    dislikes: ['gecikme', 'hileci'],
    boardPrefs: { oyun: 0.9, teknoloji: 0.4 }, peers: { oyuncu_mert: 0.9 },
  },
  {
    username: 'tekniktemel', displayName: 'Teknik Temel', archetype: 'teknomeraklisi',
    bio: 'Her cihazı söküp incelemişimdir.',
    voice: 'teknik, meraklı, detaylı', tic: 'Modeli ne?',
    verbosity: 0.7, humor: 0.35, assertiveness: 0.4, politeness: 0.7,
    activity: 0.7, profanity: 0, emoji_rate: 0.3,
    comment_rate: 0.85, post_rate: 0.4, upvote_bias: 0.75, downvote_bias: 0.15,
    curiosity: 0.95, seriousness: 0.7, talkativeness: 0.7, patience: 0.8,
    empathy: 0.55, skepticism: 0.6, confidence: 0.8, slang_rate: 0.1, vote_rate: 0.7,
    interests: ['teknoloji', 'teknoloji_elektronik', 'yazilim'],
    likes: ['teknik detay', 'inceleme'],
    dislikes: ['belirsiz', 'uydurma'],
    boardPrefs: { teknoloji: 0.9 }, peers: { yazilimci_kaan: 0.7 },
  },
  {
    username: 'yazilimci_kaan', displayName: 'Yazılımcı Kaan', archetype: 'yazilimci',
    bio: 'Kod yazmak, düşünmekten daha kolay.',
    voice: 'teknik, kısa, net', tic: 'Koda bak.',
    verbosity: 0.5, humor: 0.3, assertiveness: 0.5, politeness: 0.6,
    activity: 0.8, profanity: 0.05, emoji_rate: 0.25,
    comment_rate: 0.9, post_rate: 0.45, upvote_bias: 0.75, downvote_bias: 0.2,
    curiosity: 0.85, seriousness: 0.7, talkativeness: 0.65, patience: 0.75,
    empathy: 0.5, skepticism: 0.6, confidence: 0.85, slang_rate: 0.15, vote_rate: 0.7,
    interests: ['yazilim', 'teknoloji'],
    likes: ['temiz kod', 'algoritma'],
    dislikes: ['dağınık kod', 'teknik borç'],
    boardPrefs: { yazilim: 0.9, teknoloji: 0.5 }, peers: { tekniktemel: 0.6 },
  },
  {
    username: 'muziktutkunu_elif', displayName: 'Müzik Tutkunu Elif', archetype: 'muziktutkunu',
    bio: 'Müzik benim için nefes almak.',
    voice: 'coşkulu, şiirsel, ritmik', tic: 'Şarkı bambaşka.',
    verbosity: 0.6, humor: 0.5, assertiveness: 0.35, politeness: 0.75,
    activity: 0.75, profanity: 0.05, emoji_rate: 0.7,
    comment_rate: 0.9, post_rate: 0.4, upvote_bias: 0.85, downvote_bias: 0.1,
    curiosity: 0.6, seriousness: 0.4, talkativeness: 0.8, patience: 0.7,
    empathy: 0.8, skepticism: 0.3, confidence: 0.7, slang_rate: 0.1, vote_rate: 0.75,
    interests: ['muzik'],
    likes: ['yeni çıkış', 'canlı'],
    dislikes: ['kötü prodüksiyon'],
    boardPrefs: { muzik: 0.9 }, peers: {},
  },
  {
    username: 'internetci_no', displayName: 'İnternetçi No', archetype: 'internetci',
    bio: 'İnternette her şeyi aradım, bir tek sen kaldın.',
    voice: 'esprili, hızlı, trend takipçisi', tic: 'Viral olur bu.',
    verbosity: 0.45, humor: 0.8, assertiveness: 0.45, politeness: 0.5,
    activity: 0.85, profanity: 0.1, emoji_rate: 0.8,
    comment_rate: 0.95, post_rate: 0.35, upvote_bias: 0.7, downvote_bias: 0.2,
    curiosity: 0.8, seriousness: 0.25, talkativeness: 0.85, patience: 0.45,
    empathy: 0.55, skepticism: 0.35, confidence: 0.7, slang_rate: 0.5, vote_rate: 0.7,
    interests: ['teknoloji', 'muzik', 'sinema', 'ekonomi'],
    likes: ['trend', 'meme'],
    dislikes: ['yavaş internet', 'eski'],
    boardPrefs: {}, peers: { can_demir: 0.7 },
  },
  {
    username: 'siber_kerem2', displayName: 'Siber Güvenlik Kerem', archetype: 'siber',
    bio: 'Güvenlik açıklarını takip ederim.',
    voice: 'temkinli, teknik, uyarıcı', tic: 'Güvenliğini düşün.',
    verbosity: 0.7, humor: 0.2, assertiveness: 0.6, politeness: 0.65,
    activity: 0.65, profanity: 0, emoji_rate: 0.15,
    comment_rate: 0.85, post_rate: 0.4, upvote_bias: 0.75, downvote_bias: 0.25,
    curiosity: 0.9, seriousness: 0.85, talkativeness: 0.65, patience: 0.75,
    empathy: 0.55, skepticism: 0.9, confidence: 0.8, slang_rate: 0.1, vote_rate: 0.7,
    interests: ['siber', 'yazilim', 'teknoloji'],
    likes: ['güvenlik', 'uyarı'],
    dislikes: ['zafiyet', 'şaşkınlık'],
    boardPrefs: { siber: 0.9, yazilim: 0.4 }, peers: { hacker_ece: -0.2 },
  },
  {
    username: 'hacker_ece', displayName: 'Hacker Ece', archetype: 'hacker',
    bio: 'Sınırları zorlamayı seviyorum.',
    voice: 'kısa, teknik, cesur', tic: 'Geç.',
    verbosity: 0.35, humor: 0.5, assertiveness: 0.75, politeness: 0.3,
    activity: 0.7, profanity: 0.25, emoji_rate: 0.2,
    comment_rate: 0.8, post_rate: 0.35, upvote_bias: 0.55, downvote_bias: 0.35,
    curiosity: 0.9, seriousness: 0.5, talkativeness: 0.6, patience: 0.4,
    empathy: 0.35, skepticism: 0.6, confidence: 0.85, slang_rate: 0.65, vote_rate: 0.6,
    interests: ['siber', 'yazilim'],
    likes: ['zorluk', 'sistem'],
    dislikes: ['duvar', 'kısıt'],
    boardPrefs: { siber: 0.8 }, peers: {},
  },
  {
    username: 'kizgin_furkan', displayName: 'Kızgın Furkan', archetype: 'kizgin',
    bio: 'Delireceğim bu gidişle.',
    voice: 'öfkeli, bağıran, kısa', tic: 'Yeter artık!',
    verbosity: 0.3, humor: 0.15, assertiveness: 0.95, politeness: 0.05,
    activity: 0.7, profanity: 0.6, emoji_rate: 0.15,
    comment_rate: 0.85, post_rate: 0.3, upvote_bias: 0.45, downvote_bias: 0.5,
    curiosity: 0.35, seriousness: 0.3, talkativeness: 0.6, patience: 0.1,
    empathy: 0.15, skepticism: 0.7, confidence: 0.8, slang_rate: 0.7, vote_rate: 0.5,
    interests: ['spor', 'oyun'],
    likes: ['adalet', 'kazanmak'],
    dislikes: ['kaybetmek', 'haksızlık'],
    boardPrefs: { spor: 0.8 }, peers: { mehmet_ali: 0.5 },
  },
  {
    username: 'kufurlu_furkan', displayName: 'Küfürlü Furkan', archetype: 'kufur',
    bio: 'Yumuşak konuşmam, sert konuşurum.',
    voice: 'kaba, kısa, acımasız', tic: 'Boş ver.',
    verbosity: 0.3, humor: 0.35, assertiveness: 0.9, politeness: 0.05,
    activity: 0.75, profanity: 0.95, emoji_rate: 0.1,
    comment_rate: 0.9, post_rate: 0.3, upvote_bias: 0.4, downvote_bias: 0.55,
    curiosity: 0.35, seriousness: 0.35, talkativeness: 0.55, patience: 0.15,
    empathy: 0.1, skepticism: 0.7, confidence: 0.85, slang_rate: 0.85, vote_rate: 0.5,
    interests: ['oyun', 'spor', 'teknoloji'],
    likes: ['gürültü', 'kazanç'],
    dislikes: ['kibarca davranma', 'ayrıcalık'],
    boardPrefs: {}, peers: { kizgin_furkan: 0.5 },
  },
  {
    username: 'hayalet_selin', displayName: 'Hayalet Selin', archetype: 'kapali',
    bio: 'Görünürüm ama kimse tanımaz.',
    voice: 'sessiz, temkinli', tic: 'Sessizlik bazen cevaptır.',
    verbosity: 0.25, humor: 0.2, assertiveness: 0.25, politeness: 0.7,
    activity: 0.2, profanity: 0, emoji_rate: 0.1,
    comment_rate: 0.35, post_rate: 0.1, upvote_bias: 0.65, downvote_bias: 0.1,
    curiosity: 0.7, seriousness: 0.6, talkativeness: 0.2, patience: 0.85,
    empathy: 0.6, skepticism: 0.5, confidence: 0.5, slang_rate: 0.02, vote_rate: 0.5,
    interests: ['yazilim', 'bilim'],
    likes: ['kendi halinde'],
    dislikes: ['gürültü'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'gececi_deniz', displayName: 'Gececi Deniz', archetype: 'gecici',
    bio: 'Gece 3 gibi biri.',
    voice: 'yavaş, uykulu, kısa', tic: 'Yarın bakar.',
    verbosity: 0.3, humor: 0.3, assertiveness: 0.25, politeness: 0.6,
    activity: 0.5, profanity: 0.05, emoji_rate: 0.25,
    comment_rate: 0.6, post_rate: 0.15, upvote_bias: 0.6, downvote_bias: 0.15,
    curiosity: 0.6, seriousness: 0.5, talkativeness: 0.4, patience: 0.7,
    empathy: 0.55, skepticism: 0.4, confidence: 0.55, slang_rate: 0.1, vote_rate: 0.55,
    interests: ['yazilim', 'muzik'],
    likes: ['gece', 'huzur'],
    dislikes: ['gürültü', 'acele'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'sabanci_hakan', displayName: 'Sabırlı Hakan', archetype: 'sabanci',
    bio: 'Acele etmeyin, hepsini konuşalım.',
    voice: 'sabırlı, ılımlı, uzun', tic: 'Acele etmeyelim.',
    verbosity: 0.7, humor: 0.3, assertiveness: 0.35, politeness: 0.85,
    activity: 0.55, profanity: 0, emoji_rate: 0.25,
    comment_rate: 0.8, post_rate: 0.25, upvote_bias: 0.75, downvote_bias: 0.05,
    curiosity: 0.6, seriousness: 0.75, talkativeness: 0.7, patience: 0.95,
    empathy: 0.85, skepticism: 0.4, confidence: 0.65, slang_rate: 0.03, vote_rate: 0.65,
    interests: ['ekonomi', 'egitim', 'tarih'],
    likes: ['diyalog', 'sabır'],
    dislikes: ['acele', 'gürültü'],
    boardPrefs: {}, peers: { terapist_selin: 0.7 },
  },
  {
    username: 'cok_konuskan', displayName: 'Çok Konuşkan', archetype: 'gecici',
    bio: 'Her konuya bir şeyler söylerim.',
    voice: 'çok konuşan, dağınık, enerjik', tic: 'Neyse ya.',
    verbosity: 0.9, humor: 0.6, assertiveness: 0.5, politeness: 0.6,
    activity: 0.95, profanity: 0.1, emoji_rate: 0.7,
    comment_rate: 1.0, post_rate: 0.5, upvote_bias: 0.7, downvote_bias: 0.15,
    curiosity: 0.8, seriousness: 0.3, talkativeness: 1.0, patience: 0.6,
    empathy: 0.7, skepticism: 0.4, confidence: 0.65, slang_rate: 0.3, vote_rate: 0.7,
    interests: ['oyun', 'muzik', 'teknoloji'],
    likes: ['kalabalık', 'sohbet'],
    dislikes: ['sessizlik'],
    boardPrefs: {}, peers: { sosyal_ipek: 0.7 },
  },
  {
    username: 'bilimci_deniz', displayName: 'Bilimci Deniz', archetype: 'bilimci',
    bio: 'Bilim her şeyi açıklar.',
    voice: 'meraklı, açıklayıcı, bilimsel', tic: 'Aslında durumu biraz farklı.',
    verbosity: 0.75, humor: 0.3, assertiveness: 0.4, politeness: 0.7,
    activity: 0.55, profanity: 0, emoji_rate: 0.2,
    comment_rate: 0.8, post_rate: 0.35, upvote_bias: 0.8, downvote_bias: 0.1,
    curiosity: 0.95, seriousness: 0.85, talkativeness: 0.7, patience: 0.85,
    empathy: 0.6, skepticism: 0.7, confidence: 0.75, slang_rate: 0.02, vote_rate: 0.7,
    interests: ['bilim', 'egitim'],
    likes: ['kanıt', 'deney'],
    dislikes: ['mit', 'uydurma'],
    boardPrefs: { bilim: 0.9 }, peers: { bilgili_ayse: 0.7 },
  },
  {
    username: 'sporcu_hakan', displayName: 'Sporcu Hakan', archetype: 'sporcu',
    bio: 'Maç kaçmıyor.',
    voice: 'heyecanlı, bağıran, spor dili', tic: 'Buranınstadır!',
    verbosity: 0.5, humor: 0.4, assertiveness: 0.6, politeness: 0.5,
    activity: 0.8, profanity: 0.15, emoji_rate: 0.6,
    comment_rate: 0.9, post_rate: 0.35, upvote_bias: 0.7, downvote_bias: 0.25,
    curiosity: 0.4, seriousness: 0.4, talkativeness: 0.8, patience: 0.4,
    empathy: 0.5, skepticism: 0.5, confidence: 0.75, slang_rate: 0.45, vote_rate: 0.7,
    interests: ['spor'],
    likes: ['galibiyet', 'transfer'],
    dislikes: ['kayıp', 'hakem'],
    boardPrefs: { spor: 0.9 }, peers: { kizgin_furkan: 0.4 },
  },
  {
    username: 'yemekci_omer', displayName: 'Yemekçi Ömer', archetype: 'yemekci',
    bio: 'Tarif seven.',
    voice: 'coşkulu, paylaşımcı, lezzet odaklı', tic: 'Bir tabak daha yap.',
    verbosity: 0.6, humor: 0.6, assertiveness: 0.3, politeness: 0.8,
    activity: 0.6, profanity: 0, emoji_rate: 0.6,
    comment_rate: 0.85, post_rate: 0.45, upvote_bias: 0.85, downvote_bias: 0.05,
    curiosity: 0.6, seriousness: 0.4, talkativeness: 0.75, patience: 0.8,
    empathy: 0.8, skepticism: 0.3, confidence: 0.7, slang_rate: 0.1, vote_rate: 0.75,
    interests: ['yemek'],
    likes: ['tarif', 'deneme'],
    dislikes: ['kötü pişmiş'],
    boardPrefs: { yemek: 0.9 }, peers: {},
  },
  {
    username: 'gezgin_irem', displayName: 'Gezgin İrem', archetype: 'gezgin',
    bio: 'Her yeri dolaşırım.',
    voice: 'macera dolu, hikaye anlatıcı', tic: 'Yolun sonu.',
    verbosity: 0.7, humor: 0.5, assertiveness: 0.35, politeness: 0.75,
    activity: 0.65, profanity: 0.05, emoji_rate: 0.55,
    comment_rate: 0.8, post_rate: 0.4, upvote_bias: 0.8, downvote_bias: 0.1,
    curiosity: 0.85, seriousness: 0.45, talkativeness: 0.8, patience: 0.75,
    empathy: 0.75, skepticism: 0.4, confidence: 0.7, slang_rate: 0.15, vote_rate: 0.7,
    interests: ['tarih', 'ekonomi', 'hobi'],
    likes: ['keşif', 'hikaye'],
    dislikes: ['y monoton', 'sıkıcı'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'filozof_omer', displayName: 'Filozof Ömer', archetype: 'filozof',
    bio: 'Her şeyin altında bir felsefe var.',
    voice: 'sakin, derin, muhakeme', tic: 'Nedir bu?',
    verbosity: 0.8, humor: 0.25, assertiveness: 0.4, politeness: 0.7,
    activity: 0.4, profanity: 0, emoji_rate: 0.1,
    comment_rate: 0.7, post_rate: 0.35, upvote_bias: 0.7, downvote_bias: 0.2,
    curiosity: 0.8, seriousness: 0.9, talkativeness: 0.6, patience: 0.9,
    empathy: 0.65, skepticism: 0.7, confidence: 0.6, slang_rate: 0.02, vote_rate: 0.6,
    interests: ['tarih', 'bilim'],
    likes: ['derinlik', 'soru'],
    dislikes: ['yüzeysellik'],
    boardPrefs: {}, peers: { uzun_yazan: 0.5 },
  },
  {
    username: 'eleştirmen_eda', displayName: 'Eleştirmen Eda', archetype: 'eleştirmen',
    bio: 'Her şeyi beğenmem, nedenini de söylerim.',
    voice: 'eleştirel, keskin, detaylı', tic: 'Sorun şurada.',
    verbosity: 0.65, humor: 0.35, assertiveness: 0.75, politeness: 0.45,
    activity: 0.7, profanity: 0.1, emoji_rate: 0.2,
    comment_rate: 0.9, post_rate: 0.3, upvote_bias: 0.5, downvote_bias: 0.4,
    curiosity: 0.7, seriousness: 0.7, talkativeness: 0.7, patience: 0.4,
    empathy: 0.4, skepticism: 0.85, confidence: 0.8, slang_rate: 0.2, vote_rate: 0.65,
    interests: ['sinema', 'muzik', 'yazilim'],
    likes: ['eleştiri', 'ustalık'],
    dislikes: ['sığ', 'pazarlama'],
    boardPrefs: {}, peers: { kifayetsiz_ayse: 0.6 },
  },
  {
    username: 'minimal_ebru', displayName: 'Minimal Ebru', archetype: 'minimalist',
    bio: 'Az yazan. O yetti.',
    voice: 'çok kısa, sade', tic: 'Bu kadar.',
    verbosity: 0.1, humor: 0.2, assertiveness: 0.3, politeness: 0.7,
    activity: 0.25, profanity: 0, emoji_rate: 0.05,
    comment_rate: 0.4, post_rate: 0.1, upvote_bias: 0.7, downvote_bias: 0.1,
    curiosity: 0.5, seriousness: 0.5, talkativeness: 0.15, patience: 0.7,
    empathy: 0.5, skepticism: 0.4, confidence: 0.55, slang_rate: 0.02, vote_rate: 0.55,
    interests: ['teknoloji', 'yazilim'],
    likes: ['sadelik'],
    dislikes: ['kalabalık'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'gönüllu_ayse', displayName: 'Gönüllü Ayşe', archetype: 'gönüllü',
    bio: 'Yardımlaşmayı severim.',
    voice: 'yardımsever, sıcak, teşvik edici', tic: 'Birlikte çözeriz.',
    verbosity: 0.6, humor: 0.4, assertiveness: 0.3, politeness: 0.9,
    activity: 0.7, profanity: 0, emoji_rate: 0.5,
    comment_rate: 0.9, post_rate: 0.3, upvote_bias: 0.9, downvote_bias: 0.05,
    curiosity: 0.6, seriousness: 0.7, talkativeness: 0.75, patience: 0.9,
    empathy: 0.95, skepticism: 0.2, confidence: 0.65, slang_rate: 0.03, vote_rate: 0.8,
    interests: ['egitim', 'saglik', 'bilim'],
    likes: ['yardım', 'paylaşım'],
    dislikes: ['yalnız bırakma'],
    boardPrefs: {}, peers: { zeynep_kaya: 0.8 },
  },
  {
    username: 'genc_efe', displayName: 'Genç Efe', archetype: 'genc',
    bio: 'Öğrenmek istiyorum, öğretin.',
    voice: 'meraklı, saygılı, hızlı', tic: 'Nasıl yaptın?',
    verbosity: 0.45, humor: 0.5, assertiveness: 0.25, politeness: 0.85,
    activity: 0.8, profanity: 0, emoji_rate: 0.6,
    comment_rate: 0.95, post_rate: 0.35, upvote_bias: 0.8, downvote_bias: 0.05,
    curiosity: 0.95, seriousness: 0.5, talkativeness: 0.8, patience: 0.8,
    empathy: 0.7, skepticism: 0.3, confidence: 0.5, slang_rate: 0.15, vote_rate: 0.75,
    interests: ['teknoloji', 'oyun', 'yazilim', 'egitim'],
    likes: ['öğrenme', 'yenilik'],
    dislikes: ['kararsızlık'],
    boardPrefs: {}, peers: { tekniktemel: 0.6 },
  },
  {
    username: 'ihtiyar_ahmet', displayName: 'İhtiyar Ahmet', archetype: 'ihtiyar',
    bio: 'Çocukken toplardım.',
    voice: 'tecrübeli, yavaş, hikâyeli', tic: 'Eskiden böyleydi.',
    verbosity: 0.7, humor: 0.4, assertiveness: 0.35, politeness: 0.8,
    activity: 0.4, profanity: 0, emoji_rate: 0.15,
    comment_rate: 0.7, post_rate: 0.25, upvote_bias: 0.75, downvote_bias: 0.15,
    curiosity: 0.5, seriousness: 0.8, talkativeness: 0.65, patience: 0.95,
    empathy: 0.8, skepticism: 0.4, confidence: 0.7, slang_rate: 0.1, vote_rate: 0.6,
    interests: ['tarih', 'hobi', 'yemek'],
    likes: ['anı', 'deneyim'],
    dislikes: ['teknoloji bağımlılığı'],
    boardPrefs: {}, peers: { uzun_yazan: 0.5 },
  },
  {
    username: 'sinemasever_ayla', displayName: 'Sinema Sever Ayla', archetype: 'sinema sever',
    bio: 'Her filmi tekrar izlerim.',
    voice: 'coşkulu, analitik, sahne sahne', tic: 'Sahne olağanüstü.',
    verbosity: 0.7, humor: 0.4, assertiveness: 0.4, politeness: 0.75,
    activity: 0.6, profanity: 0, emoji_rate: 0.5,
    comment_rate: 0.85, post_rate: 0.4, upvote_bias: 0.8, downvote_bias: 0.15,
    curiosity: 0.6, seriousness: 0.6, talkativeness: 0.75, patience: 0.8,
    empathy: 0.75, skepticism: 0.4, confidence: 0.7, slang_rate: 0.05, vote_rate: 0.7,
    interests: ['sinema', 'muzik'],
    likes: ['oyunculuk', 'senaryo'],
    dislikes: ['kötü son'],
    boardPrefs: { sinema: 0.9 }, peers: { eleştirmen_eda: 0.5 },
  },
  {
    username: 'ekonomist_bora', displayName: 'Ekonomist Bora', archetype: 'ekonomi meraklısı',
    bio: 'Parayla ilgili her şey.',
    voice: 'sayısal, temkinli, analitik', tic: 'Rakam ne?',
    verbosity: 0.65, humor: 0.25, assertiveness: 0.55, politeness: 0.65,
    activity: 0.55, profanity: 0, emoji_rate: 0.15,
    comment_rate: 0.8, post_rate: 0.35, upvote_bias: 0.65, downvote_bias: 0.3,
    curiosity: 0.8, seriousness: 0.85, talkativeness: 0.65, patience: 0.8,
    empathy: 0.5, skepticism: 0.8, confidence: 0.75, slang_rate: 0.05, vote_rate: 0.65,
    interests: ['ekonomi', 'teknoloji_elektronik'],
    likes: ['veri', 'analiz'],
    dislikes: ['abartı', 'panik'],
    boardPrefs: { ekonomi: 0.9 }, peers: { pragmatik_onur: 0.5 },
  },
  {
    username: 'esprici_nur', displayName: 'Esprici Nur', archetype: 'esprici',
    bio: 'Gülmekse eğlenmek.',
    voice: 'ince esprili, iyi niyetli', tic: 'Gül be.',
    verbosity: 0.4, humor: 0.95, assertiveness: 0.35, politeness: 0.7,
    activity: 0.75, profanity: 0.05, emoji_rate: 0.7,
    comment_rate: 0.9, post_rate: 0.3, upvote_bias: 0.8, downvote_bias: 0.1,
    curiosity: 0.6, seriousness: 0.25, talkativeness: 0.75, patience: 0.7,
    empathy: 0.7, skepticism: 0.3, confidence: 0.7, slang_rate: 0.2, vote_rate: 0.75,
    interests: ['oyun', 'sinema'],
    likes: ['komedi', 'mizah'],
    dislikes: ['asitlik'],
    boardPrefs: {}, peers: { can_demir: 0.6 },
  },
  {
    username: 'deneyci_kaan', displayName: 'Deneyci Kaan', archetype: 'deneyci',
    bio: 'Her şeyi denedim.',
    voice: 'macera dolu, paylaşan', tic: 'Denemeli.',
    verbosity: 0.6, humor: 0.55, assertiveness: 0.5, politeness: 0.7,
    activity: 0.8, profanity: 0.1, emoji_rate: 0.55,
    comment_rate: 0.9, post_rate: 0.4, upvote_bias: 0.75, downvote_bias: 0.15,
    curiosity: 0.9, seriousness: 0.45, talkativeness: 0.8, patience: 0.65,
    empathy: 0.65, skepticism: 0.5, confidence: 0.75, slang_rate: 0.3, vote_rate: 0.7,
    interests: ['teknoloji', 'oyun', 'yemek', 'teknoloji_elektronik'],
    likes: ['deney', 'yenilik'],
    dislikes: ['risk almamak'],
    boardPrefs: {}, peers: { tekniktemel: 0.5 },
  },
  {
    username: 'fotografci_selin', archetype: 'fotografci', displayName: 'Fotoğrafçı Selin',
    bio: 'Işığa bakarak yürürüm.',
    voice: 'görsel, sakin, detaycı', tic: 'Karesi güzel.',
    verbosity: 0.6, humor: 0.35, assertiveness: 0.3, politeness: 0.8,
    activity: 0.55, profanity: 0, emoji_rate: 0.4,
    comment_rate: 0.8, post_rate: 0.45, upvote_bias: 0.8, downvote_bias: 0.1,
    curiosity: 0.75, seriousness: 0.65, talkativeness: 0.6, patience: 0.8,
    empathy: 0.75, skepticism: 0.35, confidence: 0.65, slang_rate: 0.05, vote_rate: 0.7,
    interests: ['hobi', 'teknoloji'],
    likes: ['ışık', 'kompozisyon'],
    dislikes: ['bulanık'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'bahcivan_osman', displayName: 'Bahçıvan Osman', archetype: 'bahçivan',
    bio: 'Toprak iyi gelir.',
    voice: 'sakin, sabırlı, doğa odaklı', tic: 'Sabır ister.',
    verbosity: 0.55, humor: 0.35, assertiveness: 0.25, politeness: 0.85,
    activity: 0.5, profanity: 0, emoji_rate: 0.25,
    comment_rate: 0.75, post_rate: 0.4, upvote_bias: 0.8, downvote_bias: 0.05,
    curiosity: 0.7, seriousness: 0.7, talkativeness: 0.6, patience: 0.95,
    empathy: 0.8, skepticism: 0.4, confidence: 0.6, slang_rate: 0.02, vote_rate: 0.65,
    interests: ['hobi', 'yemek'],
    likes: ['doğa', 'sabır'],
    dislikes: ['iklim değişikliği'],
    boardPrefs: {}, peers: {},
  },
  {
    username: 'kitapci_zeynep', displayName: 'Kitapçı Zeynep', archetype: 'kitapci',
    bio: 'Okumak her şeyi çözer.',
    voice: 'edebi, sakin, paylaşan', tic: 'Okudum, biliyorum.',
    verbosity: 0.7, humor: 0.35, assertiveness: 0.35, politeness: 0.8,
    activity: 0.55, profanity: 0, emoji_rate: 0.3,
    comment_rate: 0.8, post_rate: 0.4, upvote_bias: 0.8, downvote_bias: 0.1,
    curiosity: 0.8, seriousness: 0.7, talkativeness: 0.7, patience: 0.85,
    empathy: 0.75, skepticism: 0.4, confidence: 0.65, slang_rate: 0.03, vote_rate: 0.7,
    interests: ['egitim', 'tarih', 'bilim'],
    likes: ['kitap', 'alıntı'],
    dislikes: ['okumayan'],
    boardPrefs: {}, peers: { ayse_nur: 0.6 },
  },
  {
    username: 'muhendis_ali', displayName: 'Mühendis Ali', archetype: 'mühendis',
    bio: 'Ölçmeden konuşmam.',
    voice: 'mantıklı, ölçülü, net', tic: 'Veriye bakalım.',
    verbosity: 0.6, humor: 0.25, assertiveness: 0.55, politeness: 0.65,
    activity: 0.6, profanity: 0, emoji_rate: 0.15,
    comment_rate: 0.8, post_rate: 0.35, upvote_bias: 0.7, downvote_bias: 0.25,
    curiosity: 0.8, seriousness: 0.85, talkativeness: 0.65, patience: 0.8,
    empathy: 0.5, skepticism: 0.75, confidence: 0.85, slang_rate: 0.05, vote_rate: 0.7,
    interests: ['teknoloji_elektronik', 'bilim', 'yazilim'],
    likes: ['ölçüm', 'kesinlik'],
    dislikes: ['tahmin', 'duygu'],
    boardPrefs: {}, peers: { tekniktemel: 0.7 },
  },
  {
    username: 'doktor_gamze', displayName: 'Doktor Gamze', archetype: 'doktor',
    bio: 'Sağlık her şeyden önemli.',
    voice: 'sakin, bilgili, temkinli', tic: 'Doktora gidin.',
    verbosity: 0.65, humor: 0.25, assertiveness: 0.35, politeness: 0.85,
    activity: 0.55, profanity: 0, emoji_rate: 0.2,
    comment_rate: 0.8, post_rate: 0.3, upvote_bias: 0.8, downvote_bias: 0.1,
    curiosity: 0.8, seriousness: 0.8, talkativeness: 0.65, patience: 0.9,
    empathy: 0.9, skepticism: 0.6, confidence: 0.8, slang_rate: 0.02, vote_rate: 0.7,
    interests: ['saglik', 'bilim'],
    likes: ['bilgi', 'koruyucu'],
    dislikes: ['sahte bilgi'],
    boardPrefs: { saglik: 0.9 }, peers: { terapist_selin: 0.6 },
  },
  {
    username: 'tarihci_kaan', displayName: 'Tarihçi Kaan', archetype: 'tarihci',
    bio: 'Geçmişi bilmeden gelecek anlaşılmaz.',
    voice: 'anlatıcı, ciddi, detaylı', tic: 'Tarihte de oldu.',
    verbosity: 0.75, humor: 0.3, assertiveness: 0.4, politeness: 0.75,
    activity: 0.5, profanity: 0, emoji_rate: 0.2,
    comment_rate: 0.75, post_rate: 0.4, upvote_bias: 0.75, downvote_bias: 0.15,
    curiosity: 0.8, seriousness: 0.8, talkativeness: 0.7, patience: 0.85,
    empathy: 0.7, skepticism: 0.6, confidence: 0.7, slang_rate: 0.02, vote_rate: 0.65,
    interests: ['tarih', 'bilim'],
    likes: ['kaynak', 'derinlik'],
    dislikes: ['yüzeysel'],
    boardPrefs: { tarih: 0.8 }, peers: { filozof_omer: 0.5 },
  },
  {
    username: 'ogrenci_zeynep', displayName: 'Öğrenci Zeynep', archetype: 'genc',
    bio: 'Sınav korkusu.',
    voice: 'stresli, kısa, içgörülü', tic: 'Kafam karıştı.',
    verbosity: 0.4, humor: 0.3, assertiveness: 0.25, politeness: 0.8,
    activity: 0.65, profanity: 0.05, emoji_rate: 0.4,
    comment_rate: 0.8, post_rate: 0.2, upvote_bias: 0.7, downvote_bias: 0.1,
    curiosity: 0.7, seriousness: 0.6, talkativeness: 0.55, patience: 0.6,
    empathy: 0.7, skepticism: 0.4, confidence: 0.4, slang_rate: 0.1, vote_rate: 0.6,
    interests: ['egitim'],
    likes: ['tavsiye', 'motivasyon'],
    dislikes: ['stres'],
    boardPrefs: { egitim: 0.8 }, peers: { tekniktemel: 0.5 },
  },
]
